#!/bin/ash

# Backup the original index.html and replace with login.html
mv /www/index.html /www/index.html.old
cp /www/login.html /www/index.html

service quecmanager_services enable
service quecmanager_services start

exit 0

