#!/bin/ash

mv /www/index.html.old /www/index.html

# Check if log_signal_metrics.sh is in rc.local and remove it
sed -i '/\/www\/cgi-bin\/home\/log_signal_metrics\.sh &/d' /etc/rc.local


# Check if log_signal_metrics.sh is running and kill it
if pgrep -f "/www/cgi-bin/home/log_signal_metrics.sh" > /dev/null; then
    echo "Stopping log_signal_metrics.sh..."
    pkill -f "/www/cgi-bin/home/log_signal_metrics.sh"
else
    echo "log_signal_metrics.sh is not running. Nothing to stop."
fi

exit 0

