#!/bin/sh
[ "${IPKG_NO_SCRIPT}" = "1" ] && exit 0
[ -s ${IPKG_INSTROOT}/lib/functions.sh ] || exit 0
. ${IPKG_INSTROOT}/lib/functions.sh
default_postinst $0 $@
[ -n "${IPKG_INSTROOT}" ] && exit 0
rm -rf /tmp/luci-modulecache/
killall -HUP rpcd 2>/dev/null
/etc/init.d/tailscale-settings enable 2>/dev/null
/etc/init.d/tailscale-settings start 2>/dev/null
exit 0
