#!/bin/ash /etc/rc.common

START=04
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/sbin/init-overlay-watchdog.sh
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile /var/run/init-overlay-watchdog.pid
    procd_set_param tracking
    procd_close_instance
}

stop_service() {
    echo "Stopping init-overlay-watchdog service"
    # `procd` will handle stopping the service and its processes
}
