#!/bin/sh /etc/rc.common

START=49
STOP=10

USE_PROCD=1

start_service() {
    echo "Starting QuecManager services"
    echo "Executed"
    echo "Starting Signal Metrics Logger"
    # Start Signal Metrics Logger
    procd_open_instance
        procd_set_param command /www/cgi-bin/services/log_signal_metrics.sh
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
    procd_close_instance
    echo "Signal Metrics Logger Running"
    echo "All QuecManager services Running"
}

stop_service() {
    # procd will handle stopping all instances automatically
    echo "Stopping QuecManager services."
}
