#!/bin/ash

service init-overlay-watchdog stop
service mount-fix stop
sleep 1
service mount-fix disable
service init-overlay-watchdog disable
echo "Filesystem structure returned to Quectel Stock"
echo "Backup exists at /data/rootfs"
exit 0