#!/bin/ash

# Backup the original index.html and replace with login.html
mv /www/index.html /www/index.html.old
cp /www/login.html /www/index.html

service quecmanager_services enable
service quecmanager_services start

service quecmanager_cell_locking enable
service quecmanager_cell_locking start

service quecprofiles enable
service quecprofiles start

service quecwatch enable
service quecwatch start

exit 0

