#!/bin/sh /etc/rc.common
START=99
STOP=10
USE_PROCD=1

start_service() {

    echo "Starting Cloudflare WARP service..."
    procd_open_instance
    procd_set_param command /bin/warp-svc
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
    echo "Cloudflare WARP service started"
}

stop_service() {
    # procd will handle stopping all instances automatically
    echo "Stopping Cloudflare WARP service"
}
