#!/bin/ash

echo "Enabling socat-at-bridge at startup"
service socat-at-bridge enable
echo "Starting socat-at-bridge"
service socat-at-bridge start
echo "/dev/ttySMD11 is now available"
echo "If you want /dev/ttySMD7 as well you can use service socat-at-bridge"

exit 0

