#!/bin/ash

if [ -f /usr/bin/rc_sync ]; then
    echo "/usr/bin/rc_sync exists. Continuing..."
else
    echo "/usr/bin/rc_sync not found. Downloading..."
    curl -fsSL https://raw.githubusercontent.com/iamromulan/quectel-rgmii-toolkit/SDXPINN/ipk-source/sdxpinn-mount-fix/root/usr/bin/rc_sync -o /usr/bin/rc_sync
    chmod +x /usr/bin/rc_sync
fi

exit 0

