#!/bin/sh /etc/rc.common

START=05
STOP=10

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/sbin/socat-at-bridge-smd7.sh
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    # procd will handle stopping all instances automatically
    echo "Stopping socat and cat instances."
}
