#!/bin/ash

# Make the init script executable
chmod +x /etc/init.d/mount-fix
chmod +x /etc/init.d/init-overlay-watchdog
chmod +x /usr/sbin/init-overlay-watchdog.sh

# Enable and start the service
service mount-fix enable
service init-overlay-watchdog enable
service mount-fix start
opkg update
opkg install inotifywait inotifywatch
service init-overlay-watchdog start
exit 0
