#!/bin/bash

if [ ! -f /tmp/modemstatus.json ]
then
	/usrdata/simpleadmin/scripts/modemstatus_parse.sh > /dev/null
fi

runcmd=$(</tmp/modemstatus.json)

echo "Content-type: text/json" 
echo ""
cat <<EOT
$runcmd